version: "3.4"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8180:8081"

  s3:
    image: scireum/s3-ninja
    ports:
      - "9000:9000"

  tusd:
    image: tusproject/tusd
    volumes:
      - ./tmp-upload:/srv/tusd-data/data
    entrypoint: ["tusd"]
    command: [
    "-hooks-http", "http://localhost:8001/tusd-hooks",
    "-hooks-http-forward-headers", "Authorization",
    "-behind-proxy",
    "-hooks-enabled-events", "pre-finish",
    ]
    network_mode: host

  nginx:
    build:
      context: nginxKludge
      dockerfile: Dockerfile.nginx
    depends_on:
      - tusd
    network_mode: host
