version: "3.4"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:connection:6379
    ports:
      - "8083:8081"

  s3-backend:
    image: scireum/s3-ninja
    ports:
      - "9000:9000"
