import { transcodeToWebP } from "../../image/transcoders/transcodeToWebP.js"
import type { TranscoderDescriptor } from "../../transcoding/types.js"

type WebPDescriptor<N extends string> = TranscoderDescriptor<
  N,
  ReturnType<typeof transcodeToWebP>
>

export type ThumbnailDescriptor<N extends string> = WebPDescriptor<N> & {
  width: number
  height: number
}

const desiredDimensions: Record<string, [number, number]> = {
  large: [1280, 720],
  medium: [852, 480],
  small: [360, 640],
}

// Returns a list of descriptors for thumbnails generated by default.
export const desiredThumbnails = (): ThumbnailDescriptor<any>[] => {
  return Object.entries(desiredDimensions).map(([key, dimensions]) => {
    const [width, height] = dimensions

    return {
      name: `thumbnail-${key}`,
      mime: "image/webp",
      width,
      height,
      transcode: transcodeToWebP(width, height),
    }
  })
}
