-- CreateTable
CREATE TABLE "IngestJob" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

-- CreateTable
CREATE TABLE "Asset" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "videoID" INTEGER NOT NULL,
    "assetType" TEXT NOT NULL,
    FOREIGN KEY ("videoID") REFERENCES "Video" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Video" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "legacyID" INTEGER NOT NULL
);
